# Generated by ts2python version 0.8.2 on 2026-06-07 22:19:26.888441
# compatibility level: Python 3.12 and above


import sys
from enum import Enum, IntEnum

from typing import Union, Optional, Any, Generic, TypeVar, Callable, List, \
    Iterable, Iterator, Tuple, Dict, TypedDict, NotRequired, Literal, TypeAlias, \
    Awaitable, Self
try:
    from typing import ReadOnly
except ImportError:
    ReadOnly = Union


source_hash__ = "40b3cb6de98b8da40ede91612b3f7365"


##### BEGIN OF ts2python generated code


# Copyright © 2017-2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: Apache-2.0
# / Bridge types — mirrors the serialization in src/peg/json.ts
# / and the structure of grammar/tatsu.json.

# eslint-disable @typescript-eslint/no-empty-object-type


class BaseExp(TypedDict):
    pass


class BoxExp(BaseExp, TypedDict):
    exp: 'Exp'


class NamedBoxExp(BoxExp, TypedDict):
    name: str


class NullExp(BaseExp, TypedDict):
    pass


class CutExp(BaseExp, TypedDict):
    pass


class VoidExp(BaseExp, TypedDict):
    pass


class FailExp(BaseExp, TypedDict):
    pass


class DotExp(BaseExp, TypedDict):
    pass


class EofExp(BaseExp, TypedDict):
    pass


class EolExp(BaseExp, TypedDict):
    pass


class EmptyClosureExp(BaseExp, TypedDict):
    pass


class TokenExp(BaseExp, TypedDict):
    token: str


class PatternExp(BaseExp, TypedDict):
    pattern: str


class ConstantExp(BaseExp, TypedDict):
    literal: Any


class AlertExp(BaseExp, TypedDict):
    literal: str
    level: float


# ── Call / reference ───────────────────────────────────────────────


class CallExp(BaseExp, TypedDict):
    name: str


class RuleIncludeExp(BaseExp, TypedDict):
    name: str


# ── Unary: one child ───────────────────────────────────────────────


class GroupExp(BoxExp, TypedDict):
    pass


class SkipGroupExp(BoxExp, TypedDict):
    pass


class LookaheadExp(BoxExp, TypedDict):
    pass


class NegativeLookaheadExp(BoxExp, TypedDict):
    pass


class SkipToExp(BoxExp, TypedDict):
    pass


class AltExp(BoxExp, TypedDict):
    pass


class OptionalExp(BoxExp, TypedDict):
    pass


class ClosureExp(BoxExp, TypedDict):
    pass


class PositiveClosureExp(BoxExp, TypedDict):
    pass


class OverrideExp(BoxExp, TypedDict):
    pass


class OverrideListExp(BoxExp, TypedDict):
    pass


class NamedExp(NamedBoxExp, TypedDict):
    pass


class NamedListExp(NamedBoxExp, TypedDict):
    pass


class JoinExp(BoxExp, TypedDict):
    sep: 'Exp'


class PositiveJoinExp(BoxExp, TypedDict):
    sep: 'Exp'


class GatherExp(BoxExp, TypedDict):
    sep: 'Exp'


class PositiveGatherExp(BoxExp, TypedDict):
    sep: 'Exp'


# ── N-ary: array of children ───────────────────────────────────────


class SeqExp(BaseExp, TypedDict):
    sequence: List['Exp']


class ChoiceExp(BaseExp, TypedDict):
    options: List['Exp']


# ── Discriminated union of all expression shapes ───────────────────

type Exp = NullExp | CutExp | VoidExp | FailExp | DotExp | EofExp | EolExp | EmptyClosureExp | TokenExp | PatternExp | ConstantExp | AlertExp | CallExp | RuleIncludeExp | GroupExp | SkipGroupExp | LookaheadExp | NegativeLookaheadExp | SkipToExp | AltExp | OptionalExp | ClosureExp | PositiveClosureExp | OverrideExp | OverrideListExp | NamedExp | NamedListExp | JoinExp | PositiveJoinExp | GatherExp | PositiveGatherExp | SeqExp | ChoiceExp


# ── Rule ───────────────────────────────────────────────────────────


class Rule(TypedDict):
    name: str
    params: List[str]
    kwparams: Dict[str, str]
    decorators: List[str]
    base: str | None
    is_name: bool
    is_tokn: bool
    no_memo: bool
    no_stak: bool
    is_memo: bool
    is_lrec: bool
    exp: 'Exp'


# ── Grammar ────────────────────────────────────────────────────────


class Grammar(TypedDict):
    name: str
    directives: Dict[str, Any]
    keywords: List[str]
    rules: List[Rule]


##### END OF ts2python generated code
