# Generated by ts2python version 0.8.2 on 2026-06-07 15:07:01.005016
# compatibility level: Python 3.12 and above


import sys
from enum import Enum, IntEnum
from typing import (
    Any,
    Awaitable,
    Callable,
    Dict,
    Generic,
    Iterable,
    Iterator,
    List,
    Literal,
    NotRequired,
    Optional,
    Self,
    Tuple,
    TypeAlias,
    TypedDict,
    TypeVar,
    Union,
)

try:
    from typing import ReadOnly
except ImportError:
    ReadOnly = Union


source_hash__ = "7bc2844d25206af759ebb26aec44998f"


##### BEGIN OF ts2python generated code


# Copyright © 2017-2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: Apache-2.0
# / Bridge types — mirrors the serialization in src/peg/json.ts
# / and the structure of grammar/tatsu.json.


class Exp(TypedDict):
    """Base type for all PEG expression nodes in the compiled grammar."""


class BoxExp(Exp, TypedDict):
    exp: "AnyExp"


class NamedBoxExp(BoxExp, TypedDict):
    name: str


class NullExp(Exp, TypedDict):
    pass


class CutExp(Exp, TypedDict):
    pass


class VoidExp(Exp, TypedDict):
    pass


class FailExp(Exp, TypedDict):
    pass


class DotExp(Exp, TypedDict):
    pass


class EofExp(Exp, TypedDict):
    pass


class EolExp(Exp, TypedDict):
    pass


class EmptyClosureExp(Exp, TypedDict):
    pass


class TokenExp(Exp, TypedDict):
    token: str


class PatternExp(Exp, TypedDict):
    pattern: str


class ConstantExp(Exp, TypedDict):
    literal: Any


class AlertExp(Exp, TypedDict):
    literal: str
    level: float


# ── Call / reference ───────────────────────────────────────────────


class CallExp(Exp, TypedDict):
    name: str


class RuleIncludeExp(Exp, TypedDict):
    name: str


# ── Unary: one child ───────────────────────────────────────────────


class GroupExp(BoxExp, TypedDict):
    pass


class SkipGroupExp(BoxExp, TypedDict):
    pass


class LookaheadExp(BoxExp, TypedDict):
    pass


class NegativeLookaheadExp(BoxExp, TypedDict):
    pass


class SkipToExp(BoxExp, TypedDict):
    pass


class AltExp(BoxExp, TypedDict):
    pass


class OptionalExp(BoxExp, TypedDict):
    pass


class ClosureExp(BoxExp, TypedDict):
    pass


class PositiveClosureExp(BoxExp, TypedDict):
    pass


class OverrideExp(BoxExp, TypedDict):
    pass


class OverrideListExp(BoxExp, TypedDict):
    pass


class NamedExp(NamedBoxExp, TypedDict):
    pass


class NamedListExp(NamedBoxExp, TypedDict):
    pass


class JoinExp(BoxExp, TypedDict):
    sep: "AnyExp"


class PositiveJoinExp(BoxExp, TypedDict):
    sep: "AnyExp"


class GatherExp(BoxExp, TypedDict):
    sep: "AnyExp"


class PositiveGatherExp(BoxExp, TypedDict):
    sep: "AnyExp"


# ── N-ary: array of children ───────────────────────────────────────


class SeqExp(Exp, TypedDict):
    sequence: List["AnyExp"]


class ChoiceExp(Exp, TypedDict):
    options: List["AnyExp"]


# ── Discriminated union of all expression shapes ───────────────────

type AnyExp = (
    NullExp
    | CutExp
    | VoidExp
    | FailExp
    | DotExp
    | EofExp
    | EolExp
    | EmptyClosureExp
    | TokenExp
    | PatternExp
    | ConstantExp
    | AlertExp
    | CallExp
    | RuleIncludeExp
    | GroupExp
    | SkipGroupExp
    | LookaheadExp
    | NegativeLookaheadExp
    | SkipToExp
    | AltExp
    | OptionalExp
    | ClosureExp
    | PositiveClosureExp
    | OverrideExp
    | OverrideListExp
    | NamedExp
    | NamedListExp
    | JoinExp
    | PositiveJoinExp
    | GatherExp
    | PositiveGatherExp
    | SeqExp
    | ChoiceExp
)


# ── Rule ───────────────────────────────────────────────────────────


class Rule(TypedDict):
    """A single PEG rule with name, params, decorators, and body expression."""

    name: str
    params: List[str]
    kwparams: Dict[str, str]
    decorators: List[str]
    base: str | None
    is_name: bool
    is_tokn: bool
    no_memo: bool
    no_stak: bool
    is_memo: bool
    is_lrec: bool
    exp: "AnyExp"


# ── Grammar ────────────────────────────────────────────────────────


class Grammar(TypedDict):
    """A compiled PEG grammar: name, directives, keywords, and rules."""

    name: str
    directives: Dict[str, Any]
    keywords: List[str]
    rules: List[Rule]


##### END OF ts2python generated code
