# Generated by ts2python version 0.8.2 on 2026-06-07 10:01:00.581027
# compatibility level: Python 3.12 and above


import sys
from enum import Enum, IntEnum

from typing import Union, Optional, Any, Generic, TypeVar, Callable, List, \
    Iterable, Iterator, Tuple, Dict, TypedDict, NotRequired, Literal, TypeAlias, \
    Awaitable, Self
try:
    from typing import ReadOnly
except ImportError:
    ReadOnly = Union


source_hash__ = "7651478f318c30c219c1fb6033f42878"


##### BEGIN OF ts2python generated code


class RuleJSON(TypedDict):
    symbol: str
    expression: str


class GrammarJSON(TypedDict):
    name: str
    rules: List[RuleJSON]
    directives: Dict[str, str]


class ParseNode(TypedDict):
    symbol: str
    text: str
    children: List['ParseNode']
    start: float
    end: float


##### END OF ts2python generated code
