# Generated by ts2python version 0.8.2 on 2026-06-07 13:12:51.563313
# compatibility level: Python 3.7 and above


import sys
from enum import Enum, IntEnum

from typing import Union, Optional, Any, Generic, TypeVar, Callable, List, \
    Iterable, Iterator, Tuple, Dict, Awaitable


try:
    from ts2python.typeddict_shim import TypedDict, GenericTypedDict, NotRequired, Literal, \
        ReadOnly, TypeAlias
    # Override typing.TypedDict for Runtime-Validation
except ImportError:
    print("Module ts2python.typeddict_shim not found. Only coarse-grained "
          "runtime type-validation of TypedDicts possible")
    try:
        from typing import TypedDict, Literal
    except ImportError:
        try:
            from ts2python.typing_extensions import TypedDict, Literal
        except ImportError:
            print(f'Please install the "typing_extensions" module via the shell '
                  f'command "# pip install typing_extensions" before running '
                  f'{__file__} with Python-versions <= 3.8!')
    try:
        from typing_extensions import NotRequired, ReadOnly, TypeAlias
    except ImportError:
        NotRequired = Optional
        ReadOnly = Union
        TypeAlias = Any
    GenericMeta = type
    class _GenericTypedDictMeta(GenericMeta):
        def __new__(cls, name, bases, ns, total=True):
            return type.__new__(_GenericTypedDictMeta, name, (dict,), ns)
        __call__ = dict
    GenericTypedDict = _GenericTypedDictMeta('TypedDict', (dict,), {})
    GenericTypedDict.__module__ = __name__


source_hash__ = "6f75de470d0b780a02a5c513716d3810"


##### BEGIN OF ts2python generated code


# Bridge types — mirrors the serialization in src/peg/json.ts
# and the structure of grammar/tatsu.json.

# ── Base ───────────────────────────────────────────────────────────


class Exp(TypedDict):
    pass


class BoxExp(Exp, TypedDict):
    exp: 'AnyExp'


class NamedBoxExp(BoxExp, TypedDict):
    name: str


# ── Leaf: no payload ───────────────────────────────────────────────


class NullExp(Exp, TypedDict):
    pass


class CutExp(Exp, TypedDict):
    pass


class VoidExp(Exp, TypedDict):
    pass


class FailExp(Exp, TypedDict):
    pass


class DotExp(Exp, TypedDict):
    pass


class EofExp(Exp, TypedDict):
    pass


class EolExp(Exp, TypedDict):
    pass


class EmptyClosureExp(Exp, TypedDict):
    pass


class TokenExp(Exp, TypedDict):
    token: str


class PatternExp(Exp, TypedDict):
    pattern: str


class ConstantExp(Exp, TypedDict):
    literal: Any


class AlertExp(Exp, TypedDict):
    literal: str
    level: float


# ── Call / reference ───────────────────────────────────────────────


class CallExp(Exp, TypedDict):
    name: str


class RuleIncludeExp(Exp, TypedDict):
    name: str


# ── Unary: one child ───────────────────────────────────────────────


class GroupExp(BoxExp, TypedDict):
    pass


class SkipGroupExp(BoxExp, TypedDict):
    pass


class LookaheadExp(BoxExp, TypedDict):
    pass


class NegativeLookaheadExp(BoxExp, TypedDict):
    pass


class SkipToExp(BoxExp, TypedDict):
    pass


class AltExp(BoxExp, TypedDict):
    pass


class OptionalExp(BoxExp, TypedDict):
    pass


class ClosureExp(BoxExp, TypedDict):
    pass


class PositiveClosureExp(BoxExp, TypedDict):
    pass


class OverrideExp(BoxExp, TypedDict):
    pass


class OverrideListExp(BoxExp, TypedDict):
    pass


class NamedExp(NamedBoxExp, TypedDict):
    pass


class NamedListExp(NamedBoxExp, TypedDict):
    pass


class JoinExp(BoxExp, TypedDict):
    sep: 'AnyExp'


class PositiveJoinExp(BoxExp, TypedDict):
    sep: 'AnyExp'


class GatherExp(BoxExp, TypedDict):
    sep: 'AnyExp'


class PositiveGatherExp(BoxExp, TypedDict):
    sep: 'AnyExp'


# ── N-ary: array of children ───────────────────────────────────────


class SeqExp(Exp, TypedDict):
    sequence: List['AnyExp']


class ChoiceExp(Exp, TypedDict):
    options: List['AnyExp']


# ── Discriminated union of all expression shapes ───────────────────

AnyExp = Union[NullExp, CutExp, VoidExp, FailExp, DotExp, EofExp, EolExp, EmptyClosureExp, TokenExp, PatternExp, ConstantExp, AlertExp, CallExp, RuleIncludeExp, GroupExp, SkipGroupExp, LookaheadExp, NegativeLookaheadExp, SkipToExp, AltExp, OptionalExp, ClosureExp, PositiveClosureExp, OverrideExp, OverrideListExp, NamedExp, NamedListExp, JoinExp, PositiveJoinExp, GatherExp, PositiveGatherExp, SeqExp, ChoiceExp]


# ── Rule ───────────────────────────────────────────────────────────


class Rule(TypedDict):
    name: str
    params: List[str]
    kwparams: Dict[str, str]
    decorators: List[str]
    base: Union[str, None]
    is_name: bool
    is_tokn: bool
    no_memo: bool
    no_stak: bool
    is_memo: bool
    is_lrec: bool
    exp: AnyExp


# ── Grammar ────────────────────────────────────────────────────────


class Grammar(TypedDict):
    name: str
    directives: Dict[str, Any]
    keywords: List[str]
    rules: List[Rule]


##### END OF ts2python generated code
