# Copyright (c) 2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: BSD-4-Clause

name: test publish to test.pypi

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/tsemekwes
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: git diff HEAD --name-only after checkout
        run: git diff HEAD --name-only

      - uses: oven-sh/setup-bun@v2
      - uses: astral-sh/setup-uv@v7

      - name: git diff HEAD --name-only after setup
        run: git diff HEAD --name-only

      - name: install just
        run: sudo apt-get update -qq && sudo apt-get install -y -qq just

      - name: git diff HEAD --name-only after just
        run: git diff HEAD --name-only

      - name: install tools
        run: just tools

      - name: git diff HEAD --name-only after tools
        run: git diff HEAD --name-only

      - name: build
        run: just py-build

      - name: git diff HEAD --name-only after build
        run: git diff HEAD --name-only

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
          skip-existing: true
